version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: app
      APP_PORT: 3710

  app:
    image: egzola/bitbalance:1.0.11
    user: "1000:1000"
    stop_grace_period: 1m
    restart: on-failure

    environment:
      PORT: 3710
      ELECTRUM_HOST: $APP_ELECTRS_NODE_IP
      ELECTRUM_PORT: $APP_ELECTRS_NODE_PORT

    volumes:
      - ${APP_DATA_DIR}:/data

    networks:
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true